### ISSUE TITLE
Minor MLP typo

### ISSUE THREAD

**Issue by gregcanal** [JordanAsh/badge#13]
Hey Jordan, lm2 isn't actually used in this MLP implementation: https://github.com/JordanAsh/badge/blob/b1706005795fd150743b75bf0cd206137d806bb7/run.py#L191

This seems like a minor typo since the current functionality is consistent with the paper (two-layer perceptron: self.lm1 + self.linear), but figured I'd point it out.

Thanks

**Comment by JordanAsh** [comment]
good catch!
